/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hostelmanagement;

import static hostelmanagement.Admin_reg.image2buf;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author user
 */
public class Student_Registration extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    String sql;
    public static boolean isChanged2=false;
    public File f;
    String login_time;
    public Student_Registration() {
        initComponents();
        setdefpic();
        con=Connection_class.getConnection();
        add2table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        holder2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        othernames = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        state = new javax.swing.JComboBox<>();
        lga = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        regNo = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rows = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        show_user = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 109, 65));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Other Names");

        holder2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 2));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Phone");

        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jButton2.setText("Capture");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("State");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setText("LGA");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setText("Date of Birth");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel12.setText("Registration Number");

        gender.add(female);
        female.setText("Female");

        gender.add(male);
        male.setText("Male");

        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        state.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stateItemStateChanged(evt);
            }
        });

        lga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        regNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        save.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hostelmanagement/EXIT.PNG"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("-");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(544, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Total No. of Registered:");

        rows.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        jLabel6.setText("Current User:");

        show_user.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(othernames, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addComponent(holder2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(88, 88, 88)
                        .addComponent(female)
                        .addGap(21, 21, 21)
                        .addComponent(male)
                        .addGap(153, 153, 153)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(101, 101, 101)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(102, 102, 102)
                        .addComponent(lga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(53, 53, 53)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(show_user, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(save)
                        .addGap(13, 13, 13)
                        .addComponent(update)
                        .addGap(11, 11, 11)
                        .addComponent(reset)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(othernames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(holder2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(female)
                            .addComponent(male))))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lga, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(show_user, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save)
                    .addComponent(update)
                    .addComponent(reset)
                    .addComponent(jLabel3)
                    .addComponent(rows, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jTable1.setBackground(new java.awt.Color(255, 204, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        Admin_interface ai =new Admin_interface();
        String ltime=this.login_time;
        ai.login_time=ltime;
        sql="SELECT username from admin_login_details where login_time=?";
        try {
            ps=con.prepareStatement(sql);
            ps.setString(1,this.login_time);
            rs=ps.executeQuery();
            if(rs.next()){
                String user_=rs.getString("username");
                ai.show_user.setText(user_);
                String query1="SELECT photo from admin_details where username=?";
                PreparedStatement ps1=con.prepareStatement(query1);
                ps1.setString(1,user_);
                ResultSet rs1=ps1.executeQuery();
                if(rs1.next()){
                    byte[] photo_=rs1.getBytes("photo");
                    ImageIcon ic1=new ImageIcon(photo_);
                    Image ic2=ic1.getImage().getScaledInstance(ai.pic_holder.getWidth(),ai.pic_holder.getHeight(),Image.SCALE_SMOOTH);
                    ai.pic_holder.setIcon(new ImageIcon(ic2));
                }
                        
               }   
        } catch (SQLException ex) {
            Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        ai.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(null);
        File f=jfc.getSelectedFile();
        String filepath=f.getAbsolutePath();
        ImageIcon icn1=new ImageIcon(filepath);
        Image img=icn1.getImage();
        Image img2=img.getScaledInstance(holder2.getWidth(),holder2.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon icn2=new ImageIcon(img2);
        holder2.setIcon(icn2);
        isChanged2=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Webcam_cap2 wcp2=new Webcam_cap2();
       wcp2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    public void setdefpic(){
        String path="C:\\Users\\user\\Documents\\NetBeansProjects\\HostelManagement\\src\\hostelmanagement\\Images\\images2.png";
        ImageIcon icn =new ImageIcon(path);
        Image img1=icn.getImage();
        Image img2=img1.getScaledInstance(holder2.getWidth(),holder2.getHeight(),Image.SCALE_SMOOTH);
        holder2.setIcon(new ImageIcon(img2));
    }
    public void add2table(){
        try {
            sql="Select * from student_details";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            this.jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            this.rows.setText(String.valueOf(this.jTable1.getRowCount()));
        } catch (SQLException ex) {
            Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    public void insert2db() throws IOException{
        Icon ic=holder2.getIcon();
        ImageIcon icn=(ImageIcon)ic;
        Image img2=icn.getImage();
        BufferedImage bfi=image2buf(img2);
        f=new File("newp2.jpg");
        ImageIO.write(bfi,"JPG",f);
        FileInputStream fin= new FileInputStream(f);
        try {
            sql="Insert into student_details (regno,firstname,othernames,email,phone,gender,state,lga,dob,photo)values(?,?,?,?,?,?,?,?,?,?)";
            ps=con.prepareStatement(sql);
            ps.setString(1,this.regNo.getText());
            ps.setString(2,this.firstname.getText());
            ps.setString(3,this.othernames.getText());
            ps.setString(4,this.email.getText());
            ps.setString(5,this.phone.getText());
            String gen;
            if(this.male.isSelected()){
            gen="M";
            }
            else{
            gen="F";
            }
            ps.setString(6,gen);
            ps.setString(7,this.state.getSelectedItem().toString());
            ps.setString(8,this.lga.getSelectedItem().toString());
            String day_=this.day.getSelectedItem().toString();
            String month_=this.month.getSelectedItem().toString();
            String year_=this.year.getSelectedItem().toString();
            String dob=day_+"/"+month_+"/"+year_;
            ps.setString(9,dob);
            ps.setBinaryStream(10,fin,fin.available());
            ps.executeUpdate();
        }catch (SQLException ex) {
            Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String em=email.getText();
        String regex_="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}";
        String num=this.phone.getText();
        if (this.firstname.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Enter your first name","Attention",JOptionPane.WARNING_MESSAGE);
            this.firstname.setBackground(Color.cyan);
            this.firstname.requestFocusInWindow();
            return;
        }
        else if (this.othernames.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Enter your last name","Attention",JOptionPane.WARNING_MESSAGE);
            this.othernames.setBackground(Color.cyan);
            this.othernames.requestFocusInWindow();
            return;
        }
        else if (this.phone.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Enter your Phone number","Attention",JOptionPane.WARNING_MESSAGE);
            this.phone.setBackground(Color.cyan);
            this.phone.requestFocusInWindow();
            return;
        }
        else if (!em.matches(regex_)){
            JOptionPane.showMessageDialog(this,"Enter a valid email address","Attention",JOptionPane.WARNING_MESSAGE);
            this.email.setBackground(Color.cyan);
            this.email.requestFocusInWindow();
            return;
        }

        else if (this.email.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Email cannot be empty","Attention",JOptionPane.WARNING_MESSAGE);
            this.email.setBackground(Color.cyan);
            this.email.requestFocusInWindow();
            return;
        }
        else if (StringUtils.isNumeric(num)==false|num.length()!=11){
            JOptionPane.showMessageDialog(this,"Please use a valid Number","Attention",JOptionPane.WARNING_MESSAGE);
            this.phone.setBackground(Color.cyan);
            this.phone.requestFocusInWindow();
        }
        else if(this.gender.getSelection()==null){
            JOptionPane.showMessageDialog(this,"Select your gender","Attention",JOptionPane.WARNING_MESSAGE);
        }
       else if (isChanged2==false){
         JOptionPane.showMessageDialog(null,"You must enter a valid picture");
      }
      else if(this.state.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null,"Enter a valid state of origin");
      }
      else if(this.lga.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null,"Enter a valid LGA");
      }
      else if(this.day.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null,"Enter a valid day");
      }
      else if(this.month.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null,"Enter a valid month");
      }
      else if(this.year.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null,"Enter a valid year");
      }
      else{
            try {
                String reg=String.valueOf(this.year.getSelectedItem());
                String reg2=reg.substring(reg.length()-1);
                String ln=this.othernames.getText().toUpperCase();
                String ln2=ln.substring(ln.length()-1);
                String no=Create_Regno.generate();
                String regNo_=reg2+ln2+"/"+no;
                this.regNo.setText(regNo_);
                insert2db();
                resetForm();
                add2table();
                JOptionPane.showMessageDialog(null,"Your Registration number is "+regNo_);
            } catch (IOException ex) {
                Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
    }//GEN-LAST:event_saveActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.state.removeAllItems();
        this.lga.removeAllItems();
        this.day.removeAllItems();
        this.year.removeAllItems();
        this.state.addItem("Select");
        this.lga.addItem("Select");
        this.day.addItem("Day");
        this.year.addItem("Year");
        for(int i=1;i<=31;i++){
            day.addItem(String.valueOf(i));
        }
        for(int h=1950;h<=2018;h++){
            year.addItem(String.valueOf(h));
        }
       this.state.addItem("Abia");
       this.state.addItem("Adamawa");
       this.state.addItem("Akwa-Ibom");
       this.state.addItem("Anambra");
       this.state.addItem("Bauchi");
       this.state.addItem("Bayelsa");
       this.state.addItem("Benue");
       this.state.addItem("Borno");
       this.state.addItem("Cross-River");
       this.state.addItem("Delta");
       this.state.addItem("Ebonyi");
       this.state.addItem("Edo");
       this.state.addItem("Ekiti");
       this.state.addItem("Enugu");
       this.state.addItem("FCT");
       this.state.addItem("Gombe");
       this.state.addItem("Imo");
       this.state.addItem("Jigawa");
       this.state.addItem("Kaduna");
       this.state.addItem("Kano");
       this.state.addItem("Katsina");
       this.state.addItem("Kebbi");
       this.state.addItem("Kogi");
       this.state.addItem("Kwara");
       this.state.addItem("Lagos");
       this.state.addItem("Nassarawa");
       this.state.addItem("Niger");
       this.state.addItem("Ogun");
       this.state.addItem("Ondo");
       this.state.addItem("Osun");
       this.state.addItem("Oyo");
       this.state.addItem("Plateau");
       this.state.addItem("Rivers");
       this.state.addItem("Sokoto");
       this.state.addItem("Taraba");
       this.state.addItem("Yobe");
       this.state.addItem("Zamfara");
    }//GEN-LAST:event_formWindowOpened

    private void stateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stateItemStateChanged
        if(this.state.getSelectedItem()=="Abia"){
            this.lga.addItem("Aba North");
            this.lga.addItem("Aba South");
            this.lga.addItem("Arochukwu");
            this.lga.addItem("Bende");
            this.lga.addItem("Isiala Ngwa North");
            this.lga.addItem("Isiala Ngwa South");
            this.lga.addItem("Ikwuano");
            this.lga.addItem("Isukwuato");
            this.lga.addItem("Obi Ngwa");
            this.lga.addItem("Ohafia");
            this.lga.addItem("Osisioma Ngwa");
            this.lga.addItem("Ugwunagbo");
            this.lga.addItem("Ukwa Eest");
            this.lga.addItem("Ukwa West");
            this.lga.addItem("Umuahia");
            this.lga.addItem("Umuahia South");
            this.lga.addItem("Umu Neochi");
        }
        if(this.state.getSelectedItem()=="Adamawa"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Demsa");
            this.lga.addItem("Fufore");
            this.lga.addItem("Ganaye");
            this.lga.addItem("Girei");
            this.lga.addItem("Gombi");
            this.lga.addItem("Guyuk");
            this.lga.addItem("Hong");
            this.lga.addItem("Jada");
            this.lga.addItem("Jimeta");
            this.lga.addItem("Lamurde");
            this.lga.addItem("Madagali");
            this.lga.addItem("Maiha");
            this.lga.addItem("Mayo-Belwa");
            this.lga.addItem("Michika");
            this.lga.addItem("Mubi-North");
            this.lga.addItem("Mubi South");
            this.lga.addItem("Numan");
            this.lga.addItem("Shelleng");
            this.lga.addItem("Song");
            this.lga.addItem("Toungo");
            this.lga.addItem("Yola North");
            this.lga.addItem("Yola South");

        }
        if(this.state.getSelectedItem()=="Akwa-Ibom"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Abak");
            this.lga.addItem("Eastern Obolo");
            this.lga.addItem("Eket");
            this.lga.addItem("Esit Eket");
            this.lga.addItem("Essiem Udim");
            this.lga.addItem("Etim Ekpo");
            this.lga.addItem("Etinan");
            this.lga.addItem("Ibeno");
            this.lga.addItem("Ibesikpo Asutan");
            this.lga.addItem("Ibiono Ibom");
            this.lga.addItem("Ika");
            this.lga.addItem("Ikono");
            this.lga.addItem("Ikot Abasi");
            this.lga.addItem("Ikot Ekpene");
            this.lga.addItem("Ini");
            this.lga.addItem("Itu");
            this.lga.addItem("Mbo");
            this.lga.addItem("Mkpat Enin");
            this.lga.addItem("Nsit Ibom");
            this.lga.addItem("Nsit Ubium");
            this.lga.addItem("Obot Akara");
            this.lga.addItem("Okobo");
            this.lga.addItem("Onna");
            this.lga.addItem("Orukanam");
            this.lga.addItem("Oron");
            this.lga.addItem("Oruko Ete");
            this.lga.addItem("Udung Uko");
            this.lga.addItem("Ukanafun");
            this.lga.addItem("Uruan");
            this.lga.addItem("Urue Offong/Oruko");
            this.lga.addItem("Uyo");
        }
        if(this.state.getSelectedItem()=="Anambra"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Aguata");
            this.lga.addItem("Anambra East");
            this.lga.addItem("Anambra West");
            this.lga.addItem("Anaocha");
            this.lga.addItem("Awka North");
            this.lga.addItem("Awka South");
            this.lga.addItem("Anyamelum");
            this.lga.addItem("Dunukofia");
            this.lga.addItem("Ekwusigo");
            this.lga.addItem("Idemili North");
            this.lga.addItem("Idemili South");
            this.lga.addItem("Ihiala");
            this.lga.addItem("Njikoka");
            this.lga.addItem("Nnewi North");
            this.lga.addItem("Nnewi South");
            this.lga.addItem("Ogbaru");
            this.lga.addItem("Onitsha North");
            this.lga.addItem("Onitsha South");
            this.lga.addItem("Oruma North");
            this.lga.addItem("Orumba SOuth");
            this.lga.addItem("Oyi");
        }
        if(this.state.getSelectedItem()=="Bauchi"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Alkaleri");
            this.lga.addItem("Bauchi");
            this.lga.addItem("Bogoro");
            this.lga.addItem("Darazo");
            this.lga.addItem("Dambian");
            this.lga.addItem("Dass");
            this.lga.addItem("Gamawa");
            this.lga.addItem("Ganjuwa");
            this.lga.addItem("Giade");
            this.lga.addItem("Itas/Gadau");
            this.lga.addItem("Jama`are");
            this.lga.addItem("Katagum");
            this.lga.addItem("Kirfi");
            this.lga.addItem("Misau");
            this.lga.addItem("Ningi");
            this.lga.addItem("Shira");
            this.lga.addItem("Tafawa-Balewa");
            this.lga.addItem("Toro");
            this.lga.addItem("Waji");
            this.lga.addItem("Zaki");
        }
        if(this.state.getSelectedItem()=="Bayelsa"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Brass");
            this.lga.addItem("Ekeremor");
            this.lga.addItem("Kolok/Opokuma");
            this.lga.addItem("Nembe");
            this.lga.addItem("Ogbia");
            this.lga.addItem("Sagbama");
            this.lga.addItem("Southern Ijaw");
            this.lga.addItem("Yenagoa");
        }
        if (this.state.getSelectedItem()=="Benue"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Ador");
            this.lga.addItem("Agatu");
            this.lga.addItem("Apa");
            this.lga.addItem("Buruku");
            this.lga.addItem("Gboko");
            this.lga.addItem("Guma");
            this.lga.addItem("Gwer east");
            this.lga.addItem("Gwer west");
            this.lga.addItem("Kastina,-ala");
            this.lga.addItem("Konshisha");
            this.lga.addItem("Kwande");
            this.lga.addItem("Logo");
            this.lga.addItem("Makurdii");
            this.lga.addItem("Obi");
            this.lga.addItem("Ogbadibo");
            this.lga.addItem("Ohimini");
            this.lga.addItem("Oju");
            this.lga.addItem("Okpokwu");
            this.lga.addItem("Oturkpo");
            this.lga.addItem("Tarka");
            this.lga.addItem("Ukum");
            this.lga.addItem("Ushongo");
            this.lga.addItem("Vandekya");
        }
        if(this.state.getSelectedItem()=="Borno"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Abadan");
            this.lga.addItem("Askira/Uba");
            this.lga.addItem("Bama");
            this.lga.addItem("Bayo");
            this.lga.addItem("Biu");
            this.lga.addItem("Chibok");
            this.lga.addItem("Damboa");
            this.lga.addItem("Dikwa");
            this.lga.addItem("Gubio");
            this.lga.addItem("Guzamala");
            this.lga.addItem("Gwoza");
            this.lga.addItem("Hawul");
            this.lga.addItem("Jere");
            this.lga.addItem("Kaga");
            this.lga.addItem("Kalka/Balge");
            this.lga.addItem("Konduga");
            this.lga.addItem("Kukawa");
            this.lga.addItem("Kwaya-kusar");
            this.lga.addItem("Mafa");
            this.lga.addItem("Magumeri");
            this.lga.addItem("Maiduguri");
            this.lga.addItem("Marte");
            this.lga.addItem("Mobbar");
            this.lga.addItem("Monguno");
            this.lga.addItem("Ngala");
            this.lga.addItem("Nganzai");
            this.lga.addItem("Shani");
        }
        if(this.lga.getSelectedItem()=="Cross-River"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Abi");
            this.lga.addItem("Akampa");
            this.lga.addItem("Akpabuyo");
            this.lga.addItem("Bakassi");
            this.lga.addItem("Bekwara");
            this.lga.addItem("Biase");
            this.lga.addItem("Boki");
            this.lga.addItem("Calabar-South");
            this.lga.addItem("Etung");
            this.lga.addItem("Ikom");
            this.lga.addItem("Obanliku");
            this.lga.addItem("Obubra");
            this.lga.addItem("Obudu");
            this.lga.addItem("Odukpani");
            this.lga.addItem("Ogoja");
            this.lga.addItem("Ugep-North");
            this.lga.addItem("Yala");
            this.lga.addItem("Yarkur");
        }
        if(this.state.getSelectedItem()=="Delta"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Aniocha North");
            this.lga.addItem("Anioha South");
            this.lga.addItem("Bomadi");
            this.lga.addItem("Burutu");
            this.lga.addItem("Ethiope East");
            this.lga.addItem("Ethiope West");
            this.lga.addItem("Ika North-East");
            this.lga.addItem("Ika South");
            this.lga.addItem("Isoko North");
            this.lga.addItem("Isoko South");
            this.lga.addItem("Ndokwa East");
            this.lga.addItem("Ndokwa West");
            this.lga.addItem("Okpe");
            this.lga.addItem("Oshimili North");
            this.lga.addItem("Oshimili South");
            this.lga.addItem("Patani");
            this.lga.addItem("Sapele");
            this.lga.addItem("Udu");
            this.lga.addItem("Ughelli South");
            this.lga.addItem("Ughelli North");
            this.lga.addItem("Ukwuani");
            this.lga.addItem("Uvwie");
            this.lga.addItem("Warri Central");
            this.lga.addItem("Warri North");
            this.lga.addItem("Warri South");
        }
        if(this.state.getSelectedItem()=="Ebonyi"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Abakaliki");
            this.lga.addItem("Afikpo North");
            this.lga.addItem("Afikpo South");
            this.lga.addItem("Ebonyi");
            this.lga.addItem("Ezza");
            this.lga.addItem("Ezza South");
            this.lga.addItem("Ikwo");
            this.lga.addItem("Ishielu");
            this.lga.addItem("Ivo");
            this.lga.addItem("Ohaozara");
            this.lga.addItem("Onicha");
            this.lga.addItem("Izzi");
        }
        if(this.state.getSelectedItem()=="Edo"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Akoko-Edo");
            this.lga.addItem("Egor");
            this.lga.addItem("Essan North-East");
            this.lga.addItem("Esan South East");
            this.lga.addItem("Esan Central");
            this.lga.addItem("Esan West");
            this.lga.addItem("Etsako Central");
            this.lga.addItem("Etsako East");
            this.lga.addItem("Etsako");
            this.lga.addItem("Oredo");
            this.lga.addItem("Orhionwon");
            this.lga.addItem("Igueben");
            this.lga.addItem("Ivia North");
            this.lga.addItem("Ovia South East");
            this.lga.addItem("Ovia South West");
            this.lga.addItem("Owan West");
            this.lga.addItem("Owan South");
            this.lga.addItem("Uhunwonde");
            this.lga.addItem("Ukpoba Central");
        }
        if(this.state.getSelectedItem()=="Ekiti"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Ado Ekiti");
            this.lga.addItem("Aiyekire");
            this.lga.addItem("Efon Alaiye");
            this.lga.addItem("Ekiti South West");
            this.lga.addItem("Ekiti West");
            this.lga.addItem("Ekiti East");
            this.lga.addItem("Emure/ise");
            this.lga.addItem("Orun");
            this.lga.addItem("Ido-Osi");
            this.lga.addItem("Ijero");
            this.lga.addItem("Ikere");
            this.lga.addItem("Ikole");
            this.lga.addItem("Ilejemeje");
            this.lga.addItem("Irepodun");
            this.lga.addItem("Ise/Orun");
            this.lga.addItem("Moba");
            this.lga.addItem("Oye");

        }
        if(this.state.getSelectedItem()=="Enugu"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Awgu");
            this.lga.addItem("Aninri");
            this.lga.addItem("Enugu East");
            this.lga.addItem("Enugu South");
            this.lga.addItem("Enugu North");
            this.lga.addItem("Ezeagu");
            this.lga.addItem("Igbo Eze North");
            this.lga.addItem("Igbo Etiti");
            this.lga.addItem("Nsukka");
            this.lga.addItem("Oji River");
            this.lga.addItem("Udenu");
            this.lga.addItem("Uzo Uwani");
            this.lga.addItem("Udi");
        }
        if(this.state.getSelectedItem()=="FCT"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Gwagwalada");
            this.lga.addItem("Kuje");
            this.lga.addItem("Abaji");
            this.lga.addItem("Abuja Municipal");
            this.lga.addItem("Bwari");
            this.lga.addItem("Kwali");
        }
        if(this.state.getSelectedItem()=="Gombe"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Akko");
            this.lga.addItem("Balanga");
            this.lga.addItem("Billiri");
            this.lga.addItem("Dukku");
            this.lga.addItem("Dunakaye");
            this.lga.addItem("Gombe");
            this.lga.addItem("Kaltungo");
            this.lga.addItem("Kwami");
            this.lga.addItem("Nafada/Bajoga");
            this.lga.addItem("Shomgom");
            this.lga.addItem("Yamaltu/Deba");
        }
        if(this.state.getSelectedItem()=="Imo"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Aboh-mbaise");
            this.lga.addItem("Ahiazu-Mbaise");
            this.lga.addItem("Ehime-Mbaino");
            this.lga.addItem("Ezinhite");
            this.lga.addItem("Ideato North");
            this.lga.addItem("Ideato South");
            this.lga.addItem("Ihitte/Uboma");
            this.lga.addItem("Ikeduru");
            this.lga.addItem("Isiala");
            this.lga.addItem("Isu");
            this.lga.addItem("Mbaitoli");
            this.lga.addItem("Ngor Okpala");
            this.lga.addItem("Njaba");
            this.lga.addItem("Nwangele");
            this.lga.addItem("Nkwere");
            this.lga.addItem("Obowo");
            this.lga.addItem("Oguta");
            this.lga.addItem("Ohaji Egbema");
            this.lga.addItem("Okigwe");
            this.lga.addItem("Onuimo");
            this.lga.addItem("Orlu");
            this.lga.addItem("Orsu");
            this.lga.addItem("Oru West");
            this.lga.addItem("Oru");
            this.lga.addItem("Owerri");
            this.lga.addItem("Owerri North");
            this.lga.addItem("Owerri South");
        }
        if(this.state.getSelectedItem()=="Jigawa"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Auyo");
            this.lga.addItem("Babura");
            this.lga.addItem("Birnin- Kudu");
            this.lga.addItem("Birniwa");
            this.lga.addItem("Buji");
            this.lga.addItem("Dutse");
            this.lga.addItem("Garki");
            this.lga.addItem("Gagarawa");
            this.lga.addItem("Gumel");
            this.lga.addItem("Guri");
            this.lga.addItem("Gwaram");
            this.lga.addItem("Gwiwa");
            this.lga.addItem("Hadeji");
            this.lga.addItem("Jahun");
            this.lga.addItem("Kafin-Hausa");
            this.lga.addItem("Kaugama");
            this.lga.addItem("Kazaure");
            this.lga.addItem("Kirikasamma");
            this.lga.addItem("Kiyawa");
            this.lga.addItem("Birnin-Magaji");
            this.lga.addItem("Maigatari");
            this.lga.addItem("Malamaduri");
            this.lga.addItem("Miga");
            this.lga.addItem("Ringim");
            this.lga.addItem("Roni");
            this.lga.addItem("Sule Tankarka");
            this.lga.addItem("Taura");
            this.lga.addItem("Yankwasi");
        }
        if(this.state.getSelectedItem()=="Kaduna"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Brnin Gwari");
            this.lga.addItem("Chukun");
            this.lga.addItem("Giwa");
            this.lga.addItem("Kajuru");
            this.lga.addItem("Igabi");
            this.lga.addItem("Ikara");
            this.lga.addItem("Jaba");
            this.lga.addItem("Jema`a");
            this.lga.addItem("Kachia");
            this.lga.addItem("Kaduna North");
            this.lga.addItem("Kaduna South");
            this.lga.addItem("Kagarko");
            this.lga.addItem("Kauru");
            this.lga.addItem("Kabau");
            this.lga.addItem("Kudan");
            this.lga.addItem("Kere");
            this.lga.addItem("Makarfi");
            this.lga.addItem("Sabongari");
            this.lga.addItem("Sanga");
            this.lga.addItem("Soba");
            this.lga.addItem("Zangon-Kataf");
            this.lga.addItem("Zaria");

        }
        if(this.state.getSelectedItem()=="Kano"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Ajigi");
            this.lga.addItem("Albasu");
            this.lga.addItem("Bagwai");
            this.lga.addItem("Bebeji");
            this.lga.addItem("Bichi");
            this.lga.addItem("Bunkure");
            this.lga.addItem("Dala");
            this.lga.addItem("Dambatta");
            this.lga.addItem("Dawakin Kudu");
            this.lga.addItem("Dawakin Tofa");
            this.lga.addItem("Doguwa");
            this.lga.addItem("Fagge");
            this.lga.addItem("Gabasawa");
            this.lga.addItem("Garko");
            this.lga.addItem("Garun Mallam");
            this.lga.addItem("Gaya");
            this.lga.addItem("Gezawa");
            this.lga.addItem("Gwale");
            this.lga.addItem("Gwarzo");
            this.lga.addItem("Kano");
            this.lga.addItem("Karay");
            this.lga.addItem("Kibiya");
            this.lga.addItem("Kiru");
            this.lga.addItem("Kumbtso");
            this.lga.addItem("Kunch");
            this.lga.addItem("Kura");
            this.lga.addItem("Maidobi");
            this.lga.addItem("Makoda");
            this.lga.addItem("MInjibir Nassarawa");
            this.lga.addItem("Rano");
            this.lga.addItem("Rimin gado");
            this.lga.addItem("Rogo");
            this.lga.addItem("Shanono");
            this.lga.addItem("Sumaila");
            this.lga.addItem("Takai");
            this.lga.addItem("Tarauni");
            this.lga.addItem("Tofa");
            this.lga.addItem("Tsanyawa");
            this.lga.addItem("Tudunwada");
            this.lga.addItem("Ungogo");
            this.lga.addItem("Warawa");
            this.lga.addItem("Wudil");

        }
        if(this.state.getSelectedItem()=="Katsina"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Bakori");
            this.lga.addItem("Batagarawa");
            this.lga.addItem("Batsari");
            this.lga.addItem("Baure");
            this.lga.addItem("Bindawa");
            this.lga.addItem("Charanchi");
            this.lga.addItem("Dan- Musa");
            this.lga.addItem("Dandume");
            this.lga.addItem("Danja");
            this.lga.addItem("Daura");
            this.lga.addItem("Dutsi");
            this.lga.addItem("Dutsin `ma");
            this.lga.addItem("Faskar");
            this.lga.addItem("Ingawa");
            this.lga.addItem("Jibiya");
            this.lga.addItem("Kafur");
            this.lga.addItem("Kaita");
            this.lga.addItem("Kankara");
            this.lga.addItem("Kankiya");
            this.lga.addItem("Katsina");
            this.lga.addItem("Furfi");
            this.lga.addItem("Kusada");
            this.lga.addItem("Mai Aduwa");
            this.lga.addItem("Malumfashi");
            this.lga.addItem("Mani");
            this.lga.addItem("Mash");
            this.lga.addItem("Matazu");
            this.lga.addItem("Musawa");
            this.lga.addItem("Rimi");
            this.lga.addItem("Sabuwa");
            this.lga.addItem("Safana");
            this.lga.addItem("Sandamu");
            this.lga.addItem("Zango");
        }
        if(this.state.getSelectedItem()=="Kebbi"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Aliero");
            this.lga.addItem("Arewa Dandi");
            this.lga.addItem("Argungu");
            this.lga.addItem("Augie");
            this.lga.addItem("Bagudo");
            this.lga.addItem("Birnin Kebbi");
            this.lga.addItem("Bunza");
            this.lga.addItem("Dandi");
            this.lga.addItem("Danko");
            this.lga.addItem("Fakai");
            this.lga.addItem("Gwandu");
            this.lga.addItem("Jeda");
            this.lga.addItem("Kalgo");
            this.lga.addItem("Koko-besse");
            this.lga.addItem("Maiyaama");
            this.lga.addItem("Ngaski");
            this.lga.addItem("Sakaba");
            this.lga.addItem("Shanga");
            this.lga.addItem("Suru");
            this.lga.addItem("Wasugu");
            this.lga.addItem("Yauri");
            this.lga.addItem("Zuru");
        }
        if(this.state.getSelectedItem()=="Kogi"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Adavi");
            this.lga.addItem("Ajaokuta");
            this.lga.addItem("Ankpa");
            this.lga.addItem("Bassa");
            this.lga.addItem("Dekina");
            this.lga.addItem("Yagba East");
            this.lga.addItem("Ibaji");
            this.lga.addItem("Idah");
            this.lga.addItem("Igalamela");
            this.lga.addItem("Ijumu");
            this.lga.addItem("Kabba bunu");
            this.lga.addItem("Kogi");
            this.lga.addItem("Mopa-Muro");
            this.lga.addItem("Ofu");
            this.lga.addItem("Ogori Magongo");
            this.lga.addItem("Okehi");
            this.lga.addItem("Okene");
            this.lga.addItem("Olamaboro");
            this.lga.addItem("Omala");
            this.lga.addItem("Yagba West");

        }
        if(this.state.getSelectedItem()=="Kwara"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Asa");
            this.lga.addItem("Baruten");
            this.lga.addItem("Ede");
            this.lga.addItem("Ekiti");
            this.lga.addItem("Ifelodun");
            this.lga.addItem("Ilorin South");
            this.lga.addItem("Ilorin West");
            this.lga.addItem("Ilorin East");
            this.lga.addItem("Irepodun");
            this.lga.addItem("Isin");
            this.lga.addItem("Kaiama");
            this.lga.addItem("Moro");
            this.lga.addItem("Offa");
            this.lga.addItem("Oke Ero");
            this.lga.addItem("Oyun");
            this.lga.addItem("Pategi");
        }
        if(this.state.getSelectedItem()=="Lagos"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Agege");
            this.lga.addItem("Alimosho Ifelodun");
            this.lga.addItem("Alimosho");
            this.lga.addItem("Amuwo-Odofin");
            this.lga.addItem("Apapa");
            this.lga.addItem("Badagry");
            this.lga.addItem("Epe");
            this.lga.addItem("Eti-Osa");
            this.lga.addItem("Ibeju- Lekki");
            this.lga.addItem("Ifako/Ijaye");
            this.lga.addItem("Ikeja");
            this.lga.addItem("Ikorodu");
            this.lga.addItem("Kosofe");
            this.lga.addItem("Lagos Island");
            this.lga.addItem("Lagos Mainland");
            this.lga.addItem("Mushin");
            this.lga.addItem("Ojo");
            this.lga.addItem("Oshodi -Isolo");
            this.lga.addItem("Shomolu");
            this.lga.addItem("Surulere");

        }
        if(this.state.getSelectedItem()=="Nassarawa"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Akwanga");
            this.lga.addItem("Awe");
            this.lga.addItem("Doma");
            this.lga.addItem("Karu");
            this.lga.addItem("Keana");
            this.lga.addItem("Keffi");
            this.lga.addItem("Kokona");
            this.lga.addItem("Lafia");
            this.lga.addItem("Nassarawa");
            this.lga.addItem("Nassarawa/Eggon");
            this.lga.addItem("Obi");
            this.lga.addItem("Toto");
            this.lga.addItem("Wamba");
        }
        if(this.state.getSelectedItem()=="Niger"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Agaie");
            this.lga.addItem("Agwara");
            this.lga.addItem("Bida");
            this.lga.addItem("Borgu");
            this.lga.addItem("Bosso");
            this.lga.addItem("Chanchanga");
            this.lga.addItem("Edati");
            this.lga.addItem("Gbako");
            this.lga.addItem("Gurara");
            this.lga.addItem("Kitcha");
            this.lga.addItem("Kontagora");
            this.lga.addItem("Lapai");
            this.lga.addItem("Lavun");
            this.lga.addItem("Magama");
            this.lga.addItem("Mariga");
            this.lga.addItem("Mokwa");
            this.lga.addItem("Moshegu");
            this.lga.addItem("Muya");
            this.lga.addItem("Paiko");
            this.lga.addItem("Rafi");
            this.lga.addItem("Shiroro");
            this.lga.addItem("Suleija");
            this.lga.addItem("Tawa-Wushishi");
        }
        if(this.state.getSelectedItem()=="Ogun"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Abeokuta North");
            this.lga.addItem("Abeokuta South");
            this.lga.addItem("Ado-odo/otta");
            this.lga.addItem("Agbado North");
            this.lga.addItem("Agbado South");
            this.lga.addItem("Ewekoro");
            this.lga.addItem("Idarapo");
            this.lga.addItem("Ifo");
            this.lga.addItem("Ijebu East");
            this.lga.addItem("Ijebu North");
            this.lga.addItem("Ikenne");
            this.lga.addItem("Ilugun Alaro");
            this.lga.addItem("Imeko Afon");
            this.lga.addItem("Ipokia");
            this.lga.addItem("Obafemi/owode");
            this.lga.addItem("Odeda");
            this.lga.addItem("Odogbolu");
            this.lga.addItem("Ogun waterside");
            this.lga.addItem("Sagamu");
        }
        if(this.state.getSelectedItem()=="Ondo"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Akoko North");
            this.lga.addItem("Akoko North East");
            this.lga.addItem("Akoko South East");
            this.lga.addItem("Akoko South");
            this.lga.addItem("Akure North");
            this.lga.addItem("Akure");
            this.lga.addItem("Idanre");
            this.lga.addItem("Ifedore");
            this.lga.addItem("Ese Odo");
            this.lga.addItem("Ilaje");
            this.lga.addItem("Ilaje");
            this.lga.addItem("Oke-Igbo");
            this.lga.addItem("Irele");
            this.lga.addItem("Odigbo");
            this.lga.addItem("Okitipupa");
            this.lga.addItem("Ondo");
            this.lga.addItem("Ondo East");
            this.lga.addItem("Ose");
            this.lga.addItem("Owo");
        }
        if(this.state.getSelectedItem()=="Osun"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Atakumosa west");
            this.lga.addItem("Atakumosa east");
            this.lga.addItem("Ayeda-ade");
            this.lga.addItem("Ayedire");
            this.lga.addItem("Bolawaduro");
            this.lga.addItem("Boripe");
            this.lga.addItem("Ede");
            this.lga.addItem("Ede North");
            this.lga.addItem("Egbedore");
            this.lga.addItem("Ejigbo");
            this.lga.addItem("Ife North");
            this.lga.addItem("Ife Central");
            this.lga.addItem("Ife South");
            this.lga.addItem("Ife East");
            this.lga.addItem("Ifedayo");
            this.lga.addItem("Ifelodun");
            this.lga.addItem("Ilesha West");
            this.lga.addItem("Ila-Orangun");
            this.lga.addItem("Ilesah East");
            this.lga.addItem("Irepodun");
            this.lga.addItem("Irewole");
            this.lga.addItem("Isokan");
            this.lga.addItem("Iwo");
            this.lga.addItem("Obokun");
            this.lga.addItem("Odo-Otin");
            this.lga.addItem("Ola-Oluwa");
            this.lga.addItem("Olorunda");
            this.lga.addItem("Oriade");
            this.lga.addItem("Orolu");
            this.lga.addItem("Osogbo");
        }
        if(this.state.getSelectedItem()=="Oyo"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Afijio");
            this.lga.addItem("Akinyele");
            this.lga.addItem("Attba");
            this.lga.addItem("Atigbo");
            this.lga.addItem("Egbeda");
            this.lga.addItem("Ibadan North");
            this.lga.addItem("Ibadan Central");
            this.lga.addItem("Ibadan South East");
            this.lga.addItem("Ibadan South West");
            this.lga.addItem("Ibarapa East");
            this.lga.addItem("Ibarapa North");
            this.lga.addItem("Ido");
            this.lga.addItem("Ifedapo");
            this.lga.addItem("Ifeloju");
            this.lga.addItem("Irepo");
            this.lga.addItem("Iseyin");
            this.lga.addItem("Itesiwaju");
            this.lga.addItem("Iwajowa");
            this.lga.addItem("Iwajowa");
            this.lga.addItem("Olorunshogo");
            this.lga.addItem("Kajola");
            this.lga.addItem("Lagelu");
            this.lga.addItem("Ogbomosho North");
            this.lga.addItem("Ogbomosho South");
            this.lga.addItem("Ogo Oluwa");
            this.lga.addItem("Oluyole");
            this.lga.addItem("Ona Ara");
            this.lga.addItem("Ore Lope");
            this.lga.addItem("Orire");
            this.lga.addItem("Oyo East");
            this.lga.addItem("Oyo West");
            this.lga.addItem("Saki East");
            this.lga.addItem("Saki West");
            this.lga.addItem("Surulere");
        }
        if(this.state.getSelectedItem()=="Plateau"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Barkin/ladi");
            this.lga.addItem("Bassa");
            this.lga.addItem("Bokkos");
            this.lga.addItem("Jos North");
            this.lga.addItem("Jos East");
            this.lga.addItem("Jos South");
            this.lga.addItem("Kanam");
            this.lga.addItem("Kiyom");
            this.lga.addItem("Langtang North");
            this.lga.addItem("Langtang South");
            this.lga.addItem("Mangu");
            this.lga.addItem("Mikang");
            this.lga.addItem("Pankshin");
            this.lga.addItem("Qua`an pan");
            this.lga.addItem("Shendam");
            this.lga.addItem("Wase");
        }
        if(this.state.getSelectedItem()=="Rivers"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Abua/Odial");
            this.lga.addItem("Ahoada West");
            this.lga.addItem("Akuku toru");
            this.lga.addItem("Andoni");
            this.lga.addItem("Asari toru");
            this.lga.addItem("Bonny");
            this.lga.addItem("Degema");
            this.lga.addItem("Eleme");
            this.lga.addItem("Emohua");
            this.lga.addItem("Etche");
            this.lga.addItem("Gokana");
            this.lga.addItem("Ikwerre");
            this.lga.addItem("Oyigbo");
            this.lga.addItem("Khana");
            this.lga.addItem("Obio/Akpor");
            this.lga.addItem("Ogba/Egbema/Edoni");
            this.lga.addItem("Ogu/Bolo");
            this.lga.addItem("Okrika");
            this.lga.addItem("Omumma");
            this.lga.addItem("Opobo/Nkoro");
            this.lga.addItem("Portharcourt");
            this.lga.addItem("Tai");
        }
        if(this.state.getSelectedItem()=="Sokoto"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Binji");
            this.lga.addItem("Bodinga");
            this.lga.addItem("Dange/Shuni");
            this.lga.addItem("Gada");
            this.lga.addItem("Goronyo");
            this.lga.addItem("Gudu");
            this.lga.addItem("Gwadabawa");
            this.lga.addItem("Illella");
            this.lga.addItem("Kebbe");
            this.lga.addItem("Kware");
            this.lga.addItem("Rabah");
            this.lga.addItem("Sabon -Birni");
            this.lga.addItem("Shagari");
            this.lga.addItem("Silame");
            this.lga.addItem("Sokoto South");
            this.lga.addItem("Sokoto North");
            this.lga.addItem("Tambuwal");
            this.lga.addItem("Tangaza");
            this.lga.addItem("Tureta");
            this.lga.addItem("Wamakko");
            this.lga.addItem("Wurno");
            this.lga.addItem("Yabo");
        }
        if(this.state.getSelectedItem()=="Taraba"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Akdo-kola");
            this.lga.addItem("Bali");
            this.lga.addItem("Donga");
            this.lga.addItem("Gashaka");
            this.lga.addItem("Gassol");
            this.lga.addItem("Ibi");
            this.lga.addItem("Jalingo");
            this.lga.addItem("K/Lamido");
            this.lga.addItem("Kurmi");
            this.lga.addItem("Lau");
            this.lga.addItem("Sardauna");
            this.lga.addItem("Tarum");
            this.lga.addItem("Ussa");
            this.lga.addItem("Wukari");
            this.lga.addItem("Yorro");
            this.lga.addItem("Zing");
        }
        if(this.state.getSelectedItem()=="Yobe"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Borsari");
            this.lga.addItem("Damaturu");
            this.lga.addItem("Fika");
            this.lga.addItem("Fune");
            this.lga.addItem("Geidam");
            this.lga.addItem("Gogaram");
            this.lga.addItem("Gujba");
            this.lga.addItem("Gulani");
            this.lga.addItem("Jakusko");
            this.lga.addItem("Karasuwa");
            this.lga.addItem("Machina");
            this.lga.addItem("Nagere");
            this.lga.addItem("Nguru");
            this.lga.addItem("Potiskum");
            this.lga.addItem("Tarmua");
            this.lga.addItem("Yunusari");
            this.lga.addItem("Yusufari");
            this.lga.addItem("G ashua");
        }
        if(this.state.getSelectedItem()=="Zamfara"){
            this.lga.removeAllItems();
            this.lga.addItem("Select");
            this.lga.addItem("Anka");
            this.lga.addItem("Bukkuyum");
            this.lga.addItem("Dungudu");
            this.lga.addItem("Chafe");
            this.lga.addItem("Gummi");
            this.lga.addItem("Gusau");
            this.lga.addItem("Isa");
            this.lga.addItem("Kaura/Namoda");
            this.lga.addItem("Maradun");
            this.lga.addItem("Maru");
            this.lga.addItem("Shinkafi");
            this.lga.addItem("Talata/Mafara");
            this.lga.addItem("Zumi");
        }
    }//GEN-LAST:event_stateItemStateChanged
    public void resetForm(){
        this.firstname.setText("");
        this.othernames.setText("");
        this.phone.setText("");
        this.email.setText("");
        this.gender.clearSelection();
        this.state.setSelectedIndex(0);
        this.lga.setSelectedIndex(0);
        this.day.setSelectedIndex(0);
        this.month.setSelectedIndex(0);
        this.year.setSelectedIndex(0);
        this.regNo.setText("");
        setdefpic();
        
    }
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        resetForm();
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int row=this.jTable1.getSelectedRow();
            String reg_=this.jTable1.getValueAt(row,0).toString();
            this.regNo.setText(reg_);
            String first_=this.jTable1.getValueAt(row,1).toString();
            this.firstname.setText(first_);
            String other_=this.jTable1.getValueAt(row,2).toString();
            this.othernames.setText(other_);
            String em=this.jTable1.getValueAt(row,3).toString();
            this.email.setText(em);
            String ph_=this.jTable1.getValueAt(row,4).toString();
            this.phone.setText(ph_);
            String gen=this.jTable1.getValueAt(row,5).toString();
            if(gen.equals("M")){
                this.male.setSelected(true);
            }
            else{
                this.female.setSelected(true);
            }   String st_=this.jTable1.getValueAt(row,6).toString();
            this.state.setSelectedItem(st_);
            String lg_=this.jTable1.getValueAt(row,7).toString();
            this.lga.setSelectedItem(lg_);
            String dob_=this.jTable1.getValueAt(row,8).toString();
            String day_="",month_="",year_="";
            if(dob_.length()==10){
                day_=dob_.substring(0,1);
                month_=dob_.substring(2,5);
                year_=dob_.substring(6);
            }
            else if(dob_.length()==11){
                day_=dob_.substring(0,2);
                month_=dob_.substring(3,6);
                year_=dob_.substring(7);
            }   this.day.setSelectedItem(day_);
            this.month.setSelectedItem(month_);
            this.year.setSelectedItem(year_);
            sql="Select photo from student_details where regno=?";
            ps=con.prepareStatement(sql);
            ps.setString(1,reg_);
            rs=ps.executeQuery();
            if(rs.next()){
                byte[] dbpass=rs.getBytes("photo");
                ImageIcon iicn=new ImageIcon(dbpass);
                Image img=iicn.getImage().getScaledInstance(holder2.getWidth(),holder2.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon iicn2=new ImageIcon(img);
                holder2.setIcon(iicn2);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Student_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        JOptionPane.showMessageDialog(this,this.login_time);
    }//GEN-LAST:event_updateActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see hfirstnameoad.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstname;
    private javax.swing.ButtonGroup gender;
    public static javax.swing.JLabel holder2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lga;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField othernames;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel regNo;
    private javax.swing.JButton reset;
    private javax.swing.JLabel rows;
    private javax.swing.JButton save;
    public javax.swing.JLabel show_user;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JButton update;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
